theme: jekyll-theme-architect







#!/usr/bin/python
# -*- coding: utf8 -*-

# To generate, run in Python:
# import os
# os.urandom(48)
COOKIE_KEY = '\xb3w\x19\xde\x1e\xfa\x96sL\xd0T20,m~\x8c\xb6\x01J'\x02\x9a]\xb0\xb1\r\x9f\xbf\xb1\xe0]\xaf\x1c\x1c\x99\xd2m\\E\x04\xac\x8b\xb7\x15W\xb1s'

# GCP project info
GOOGLE_PROJECT_ID = "flow-420808"
GOOGLE_PROJECT_NO = 601517411610

# Create an oauth 2.0 web client ID from GCP console
# Configure our client ID with, authorized javascript origins:
# - https://[your-project-id].appspot.com
# - https://test-dot-[your-project-id].appspot.com (optional, to enable testing on a subversion)
# And authorised redirect URIs:
# - https://[your-project-id].appspot.com/api/auth/google/oauth2callback
GOOGLE_CLIENT_ID = "601517411610-j70i550375eg0eneqsu3nulhrv6sc9g9.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "GOCSPC-LbN29iSAy1nNObixXzOM_ymObeif"

# Create a second oauth 2.0 client ID for use on the dev server. Origins:
# - http://localhost:8080
# Redirects:
# - client secret "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"
# - http://localhost:8080/api/auth/google/oauth2callback
DEV_GOOGLE_CLIENT_ID = "601517411610-bvhn6tbh0gijf5l6fv7f2j915espjinj.apps.googleusercontent.com"

# Create a new API key from GCP console (optional)
G_MAPS_API_KEY = "AIzaSyAyKOGSXTkwXvO_ojLixdmFKlAryqa4dMU"

# AES Cypher Key (generate similarly to above with os.urandom(16))
AES_CYPHER_KEY = 'pR\x92\x08\xc7\xf1Z\x9e!\xa8\x1c\xfa\xc7\x8cL\x14'

# Good Reads (optional)
GR_API_KEY = ""
GR_SECRET = ""

# Pocket (optional)
POCKET_CONSUMER_KEY = ""

# Evernote (optional)
EVERNOTE_CONSUMER_KEY = ""
EVERNOTE_CONSUMER_SECRET = ""
EVERNOTE_DEV_TOKEN = ""

# Facebook (optional)
FB_ACCESS_TOKEN = ""
FB_VERIFY_TOKEN = ""

# Dialogflow (Previously API.AI, optional)
API_AI_AUTH_KEY = ""
API_AI_FB_CALLBACK = ""


















var client_secrets = {

	// Match with settings/secrets.py and GCP console
	G_OAUTH_CLIENT_ID: "601517411610-j70i550375eg0eneqsu3nulhrv6sc9g9.apps.googleusercontent.com",
	DEV_G_OAUTH_CLIENT_ID: "601517411610-bvhn6tbh0gijf5l6fv7f2j915espjinj.apps.googleusercontent.com",
	GOOGLE_API_KEY: "AIzaSyAyKOGSXTkwXvO_ojLixdmFKlAryqa4dMU",

	// Goodreads
	GR_API_KEY: ""
};

module.exports = client_secrets;
